# Generated by Django 5.1.4 on 2026-03-12 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProsthesisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип протеза',
                'verbose_name_plural': 'Типы протезов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Prosthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (руб.)')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('prosthesis_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prostheses', to='catalog.prosthesistype', verbose_name='Тип протеза')),
            ],
            options={
                'verbose_name': 'Протез',
                'verbose_name_plural': 'Протезы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('prosthesis', 'На протез'), ('investor', 'Инвестор')], max_length=20, verbose_name='Тип заявки')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Имя контакта')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='Email контакта')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('prosthesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='catalog.prosthesis', verbose_name='Протез')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalog.requeststatus', verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, help_text='Оставьте пустым для гостевых заявок', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='catalog.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Место проведения')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.user', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название документа')),
                ('file_url', models.CharField(max_length=500, verbose_name='URL файла')),
                ('doc_type', models.CharField(choices=[('certificate', 'Сертификат'), ('license', 'Лицензия'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип документа')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.user', verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ / сертификат',
                'verbose_name_plural': 'Документы и сертификаты',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='catalog.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата назначения')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='catalog.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='catalog.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='catalog.UserRole', to='catalog.role', verbose_name='Роли'),
        ),
    ]
