# Generated by Django 5.1.4 on 2026-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='prosthesis',
            name='image_url',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт мероприятия'),
        ),
        migrations.AddField(
            model_name='prosthesis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prostheses/', verbose_name='Изображение'),
        ),
    ]
